### ISSUE TITLE
OMG DMCA！

### ISSUE THREAD

**Issue by 360NENZ** [DuolaD/HoYoShade-RePublish#1]
**Repo got DMCA'd！**
恭喜你獲得了**miHoYo的認可**(bushi

建議把受DMCA影響的東西放到[**Backup-DMCA-Group**](https://github.com/Backup-DMCA-Group) (跑

**Comment by DuolaD** [comment]
感謝關注233...
實際上HoYoShade的DMCA是來自於MartysMods團隊的，HoYoShade早期的Releases中由於有來自中國内地視頻創作博主的支持，所以他們在HoYoShade的Releases裏添加了本該不允許重新二次分發的付費ReShade效果庫，但是現在沒事了。這個倉庫的Releases自然而然就是移除掉受DMCA影響的内容然後二次Publish，主要的意義還是在於方便後來人二次開發吧。
![image](https://github.com/DuolaD/HoYoShade-RePublish/assets/110040721/cd7fae2d-53af-4c49-b642-ba7a0504072b)

我倒是想讓米哈游直接給我來一個DMCA，但是奈何我現在在哪裏都不算出名。

**Comment by DuolaD** [comment]
我自己是由一個Private倉庫和網盤用於備份Releases的，這也是爲了方便我自己後期開發。

我之前和jutii説過我在這之前有一個晚上情緒真的挺奔潰的。
我最討厭兩個東西：大偉丘和米哈游

**Comment by DuolaD** [comment]
如果真是米哈游給DMCA的話我HoYoLAB賬號早就沒了。
我也不會再Publish New Release了。

**Comment by DuolaD** [comment]
如果你不介意的話你直接幫我Fork去這個組織裡也行（）

**Comment by 360NENZ** [comment]
其實在寫issue時就已經import完了（跑
![Screenshot_20240310_134820](https://github.com/DuolaD/HoYoShade-RePublish/assets/51311642/4aeae8a9-78b3-4fc2-8ff4-b3c13248ce02)

**Comment by DuolaD** [comment]
那沒事了（）
我等下還得去醫院呢，我可以放心的趨勢了（）

**Comment by 360NENZ** [comment]
草
忘了***release是不能import的***
只能***import tag***（
懸著的心突然***停止跳動***了（
那麼***沒能import的release***就**多麻煩您**了
已經給您[**Backup-DMCA-Group/DuolaD-HoYoShade**](https://github.com/Backup-DMCA-Group/DuolaD-HoYoShade)的**Admin**權限了

**Comment by DuolaD** [comment]
我下週週末再去在這個庫裡備份Release（雖然我自己也已經搞了Private Repo|私有網盤|本地三備份）
剛到香港，累死，又要搬磚（）
[letheriver2007 Fork的HoYoShade](https://github.com/letheriver2007/HoYoShade) Release裡就有全V2.X.X版本的HoYoShade Release Backups。
我知道這樣公開發出去可能有麻煩，但無所謂了。有麻煩再說吧。我想原作者也不會找上我的，他們也不可能總是訂著我，我也和Fork Repo沒啥關係。

**Comment by DuolaD** [comment]
哦對了如果可以的話把[琳妮特|LynetteNotFound](https://github.com/LynetteNotFound)也拉進來（）
